### ISSUE TITLE
Robot not receiving 'slack.connect' event

### ISSUE THREAD

**Issue by pedropombeiro** [grrowl/probot-slack#1]
In the README.md file, the `slack.connect` event is mentioned (https://github.com/grrowl/probot-slack#setup), but that event is not being called for me, and I don't see any reference to it in the `probot-slack` code. I just need a way to send a message to a Slack room, which is not in response to a Slack event, but rather a GitHub event. Is it possible with this package?

**Comment by pedropombeiro** [comment]
Seems like the problem is that the latest version (0.2.0) hasn't been published to npm, but current `master` also seems to be broken...

**Comment by grrowl** [comment]
my apologies, this is very alpha and was work-in-progress. i should probably un-publish from npm, you may be able to install from github directly in the mean time.

regardless, this library just wraps around slack's web and RTM APIs. I believe in the README `slack.connect` should be [`slack.connected`](https://github.com/grrowl/probot-slack/blob/master/index.js#L46).

If you do improve upon this code I'd be more than happy to transfer ownership of `probot-slack` on NPM to you. I'm unlikely to work directly on this library in the immediate future.

**Comment by pedropombeiro** [comment]
I also stopped using this package a few months ago, so I wouldn't be the best person to maintain it. Thanks for replying though 👍
